name: Torrie Hudson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.593
title: Torrie Hudson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfafb'
    - '#312a2a'
    - '#d7cfc8'
    - '#937f77'
    - '#f0a482'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
