name: Torrie Hudson
favicon: null
layout_spectrum: 0
typography_spectrum: 0.47203
title: Torrie Hudson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#292244'
    - '#f3fdff'
    - '#a4716e'
    - '#c7afab'
    - '#5a586e'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
