name: Torrie Hudson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.593
title: Torrie Hudson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7f3ed'
    - '#11110f'
    - '#656e5e'
    - '#99a99a'
    - '#564435'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
