title: Torrie Hudson
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2690655
  brandStrength: 0.4989259
  lightness: 0.3109559
  brandColors:
    - '#212121'
    - '#F0F4F5'
    - '#C6B9A9'
    - '#828C98'
    - '#62584E'
  rhythmicContrast: 0
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: Torrie Hudson
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.0585392
layout_spectrum: 0.2497315
