name: Torrie Hudson
favicon: null
layout_spectrum: 0.963019073009491
typography_spectrum: 0.15397899062372744
title: Torrie Hudson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f4f3'
    - '#594c43'
    - '#b7b8b2'
    - '#8a857f'
    - '#050505'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
