name: Torrie Hudson
favicon: null
layout_spectrum: 0.96692
typography_spectrum: 0.47203
title: Torrie Hudson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efefed'
    - '#6c6865'
    - '#b5ada6'
    - '#2e090c'
    - '#c4484d'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
